name: 'jit'
services:
  psql-pub:
    image: postgres:16.6
    networks:
      - backend
    environment:
      POSTGRES_USER: default
      POSTGRES_PASSWORD: password
      TZ: UTC
      POSTGRES_HOST_AUTH_METHOD: trust # NOTE: 開発用のため
      POSTGRES_INITDB_WAL_LEVEL: replica # wal_levelの設定
      POSTGRES_INITDB_MAX_WAL_SENDERS: 10 #max_wal_sendersの設定
      POSTGRES_INITDB_MAX_REPLICATION_SLOTS: 10 #max_replication_slotsの設定
    ports:
      - "5433:5432"
    volumes:
      - psql-pub-volume:/var/lib/postgresql/data
      - ./docker/psql-pub/postgresql.conf:/etc/postgresql/postgresql.conf
      - ./docker/psql-pub/pg_hba.conf:/etc/postgresql/pg_hba.conf
  psql-sub:
    image: postgres:16.6
    networks:
      - backend
    environment:
      POSTGRES_USER: default
      POSTGRES_PASSWORD: password
      TZ: UTC
      POSTGRES_HOST_AUTH_METHOD: trust # NOTE: 開発用のため
    ports:
      - "5434:5432"
    volumes:
      - psql-sub-volume:/var/lib/postgresql/data
      - ./docker/psql-sub/init.sh:/docker-entrypoint-initdb.d/init.sh
    depends_on:
      - psql-pub
  minio:
    image: minio/minio:RELEASE.2025-02-07T23-21-09Z-cpuv1
    volumes:
      - minio-data-1:/data
    command: server --console-address ":9001" /data
    ports:
      - "9000:9000"
      - "9001:9001"
    networks:
      - backend
    environment:
      MINIO_ROOT_USER: default
      MINIO_ROOT_PASSWORD: password
      MINIO_DEFAULT_BUCKETS: application
  vk-session: # AWS MemoryDB
    image: 'valkey/valkey:7.2'
    networks:
      - backend
    ports:
      - "6379:6379"
    volumes:
      - vk-session-data:/data
  vk-cache: # AWS ElastiCache
    image: 'valkey/valkey:8.0'
    volumes:
      - vk-cache-volume:/data
    networks:
      - backend
    ports:
      - '6380:6379'
      #  kafka-broker:
      #    image: confluentinc/cp-kafka:6.2.4 # https://hub.docker.com/r/confluentinc/cp-kafka
      #    restart: always
      #    depends_on:
      #      - zookeeper
      #    ports:
      #      - "9092:9092"
      #    environment:
      #      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_DOCKER_INTERNAL:PLAINTEXT
      #      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-broker:19092,PLAINTEXT_DOCKER_INTERNAL://localhost:9092
      #      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      #      KAFKA_ADVERTISED_HOST_NAME: kafka-broker
      #      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      #  zookeeper:
      #    image: confluentinc/cp-zookeeper:6.2.4 # https://hub.docker.com/r/confluentinc/cp-zookeeper
      #    restart: always
      #    ports:
      #      - "2181:2181"
      #    environment:
      #      ZOOKEEPER_CLIENT_PORT: "2181"
      #  cp-kafka-rest:
      #    image: confluentinc/cp-kafka-rest:6.2.4         # https://hub.docker.com/r/confluentinc/cp-kafka-rest
      #    restart: always
      #    depends_on:
      #      - "kafka-broker"
      #      - "zookeeper"
      #    environment:
      #      KAFKA_REST_BOOTSTRAP_SERVERS: "kafka-broker:19092"
      #      KAFKA_REST_CLIENT_SECURITY_PROTOCOL: "PLAINTEXT"
      #      KAFKA_REST_HOST_NAME: "cp-kafka-rest"
      #      KAFKA_REST_LISTENERS: "http://0.0.0.0:8082"
      #  kafka-topic-ui:    # 管理コンソール（http://localhost:8000）
      #    image: landoop/kafka-topics-ui:0.9.4    # https://hub.docker.com/r/landoop/kafka-topics-ui
      #    restart: always
      #    depends_on:
      #      - "kafka-broker"
      #      - "zookeeper"
      #      - "cp-kafka-rest"
      #    ports:
      #      - "8000:8000"
      #    environment:
      #      KAFKA_REST_PROXY_URL: "http://cp-kafka-rest:8082"
      #      PROXY: "true"
  ror:
    build:
      context: ./
      target: development
      args:
        COMMIT_HASH: 'abcdef'
    command: bin/rails server -p 3000 -b 0.0.0.0
    restart: always
    user: "1000:1000"
    tty: true
    stdin_open: true
    ports:
      - "3333:3000"
    volumes:
      - ./:/ror
    networks:
      - backend
    depends_on:
      - vk-cache
      - vk-session
      - minio
  chromium:
    image: seleniarm/standalone-chromium
    restart: always # コンテナが停止すると常に再起動
    environment:
      VNC_NO_PASSWORD: 1
    networks:
      - backend
      - frontend
    ports:
      - "4444:4444"
      - "7900:7900"
    depends_on:
      - ror
  firefox:
    image: selenium/standalone-firefox
    restart: always # コンテナが停止すると常に再起動
    networks:
      - backend
      - frontend
    ports:
      - "4445:4444"
      - "7901:7900"
    depends_on:
      - ror
  openobserve:
    image: public.ecr.aws/zinclabs/openobserve:latest
    restart: unless-stopped
    environment:
      ZO_ROOT_USER_EMAIL: "root@example.com"
      ZO_ROOT_USER_PASSWORD: "Complexpass#123"
    ports:
      - "5080:5080"
    volumes:
      - openobserve-volume:/data
volumes: #
  psql-pub-volume:
  psql-sub-volume:
  vk-session-data:
  vk-cache-volume:
  opensearch-volume:
  openobserve-volume:
  minio-data-1:
networks:
  backend:
  frontend:
